#!/usr/bin/env bash

set -euo pipefail

POSTGRES_HOST_PORT="${POSTGRES_HOST_PORT:-55433}"
LITELLM_HOST_PORT="${LITELLM_HOST_PORT:-14000}"
GRAFANA_HOST_PORT="${GRAFANA_HOST_PORT:-13001}"
TEMPORAL_HOST_PORT="${TEMPORAL_HOST_PORT:-17234}"
OPENCLAW_GATEWAY_HOST_PORT="${OPENCLAW_GATEWAY_HOST_PORT:-13334}"
SCHEDULER_WORKER_HOST_PORT="${SCHEDULER_WORKER_HOST_PORT:-19002}"

BASE_DATABASE_URL="${DATABASE_URL:-postgresql://app_user:password@localhost:55432/cogni_resy_helper_stack_test}"
BASE_DATABASE_SERVICE_URL="${DATABASE_SERVICE_URL:-postgresql://app_service:service_password@localhost:55432/cogni_resy_helper_stack_test}"

export DATABASE_URL="${BASE_DATABASE_URL/@localhost:55432/@localhost:${POSTGRES_HOST_PORT}}"
export DATABASE_SERVICE_URL="${BASE_DATABASE_SERVICE_URL/@localhost:55432/@localhost:${POSTGRES_HOST_PORT}}"
export DB_HOST="localhost"
export DB_PORT="${POSTGRES_HOST_PORT}"
export LITELLM_BASE_URL="http://localhost:${LITELLM_HOST_PORT}"
export GRAFANA_URL="http://localhost:${GRAFANA_HOST_PORT}"
export TEMPORAL_ADDRESS="localhost:${TEMPORAL_HOST_PORT}"
export OPENCLAW_GATEWAY_URL="http://127.0.0.1:${OPENCLAW_GATEWAY_HOST_PORT}"
export SCHEDULER_WORKER_HEALTH_URL="http://localhost:${SCHEDULER_WORKER_HOST_PORT}"
export TIGERBEETLE_ADDRESS="${TIGERBEETLE_ADDRESS:-127.0.0.1:13002}"

exec "$@"
